### ISSUE TITLE
Updates available screen shown too often

### ISSUE THREAD

**Issue by Eduard3311** [Chem4Word/Version3#17] opened 2019-10-11 08:42 UTC
A disable auto-update option should be made available.
I have searched trough the registry and the Chem4Word.V3.json settings file but no such option is available,
This proves to be quite an issue as some people prefer to update to each version manually and the pop-up that shows at each run tends to get in the way for those people.

Thanks for the time and understanding!

**Comment by MikeWilliams-UK** [comment] 2019-10-11 08:50
Thank you for using Chem4Word.

You are quite correct there is no option to disable auto update.

We do this because we are a small team of four people working in our spare time.
We can't support old versions of the application.

Why is it an issue? providing you are running the latest version it only checks once every seven days.

**Comment by MikeWilliams-UK** [comment] 2019-10-11 10:29
I have just looked through our change history and I can see that under normal conditions (when there are no errors) we reduced the frequency of checks to weekly back in Version 2 (Release 6) on 01-Sep-2016.
On an error the check is always performed.
If you are getting errors please ensure you fill in your email address in te field provided on the form.
This will then give us sufficient information to analyse your problem.

**Comment by MikeWilliams-UK** [comment] 2019-10-11 10:32
Please can you confirm which version of the Add-in that you are running.
This can be found out from the Help --> About form

**Comment by Eduard3311** [comment] 2019-10-14 08:27
First of all I would like to thank you and your team for your work and effort put into creating Chem4Word.
Second of all, regarding my issue, I have indeed upgraded to the latest version, however, I am using SCCM to deploy the application to 30 - 60 clients, the fact that auto-update cannot be disabled/unchecked is problematic during distribution since we have detection methods in place that check on what version is installed, if a newer version is installed automatically by the application the SCCM will try to push the older one again and will create a loop.

The automatic update is a good feature in of itself, the only problem is that some users prefer to update it manually to avoid distribution or policy problems.

I hope this clears things out and I am hoping that a future release of the Chem4Word will include an option to disable the automatic updates check.

**Comment by MikeWilliams-UK** [comment] 2019-10-14 09:06
Thanks for taking the time to explain your issue in more detail.

I certainly understand how the combination of your checks in conjunction with our automatic update system can cause the "loop" which you are seeing.

Because we are a very small team we only tend to release a new version every three months or more (unless there is an urgent issue).

**Comment by MikeWilliams-UK** [comment] 2019-10-14 09:13
Please can you confirm that the Automatic update prompt if canceled by the user is not shown again for 7 days.
If this is not happening then we should work together to find out why.

**Comment by MikeWilliams-UK** [comment] 2019-10-14 09:38
In that case Chem4Word is detecting an error as soon as it is being run.
When an error is detected the system immediately checks for an update.

The standard location for our user data is %localappdata%\Chem4Word.V3
On a standard home setup this is something like C:\Users\UserName\AppData\Local\Chem4Word.V3

Inside this fiolder you will find a folder named Telemetry.  This is where our logs are stored.

Please can you clear that folder, run Word, perform a chemistry operation then close down word.
Then upload the file (which should have the format yyyy-mm-dd.log) to here.

**Comment by Eduard3311** [comment] 2019-10-14 11:43
Unfortunately I am unable to upload files due to company policies.
There is also the added problem of being unable to install the new versions since our users are blocked by Group Policies. Even if the user chooses the "Update Now" option he would still be unable to update the application. So again, in this scenario, the auto update option should have the option of being disabled since the pop-up will appear without any functionality (because of the Group Policies on our part). We understand that your team is small and we can wait for a new version that adds this option in the future.

**Comment by MikeWilliams-UK** [comment] 2019-10-14 11:50
Are you able to send the log file to info@chem4word.co.uk so that we can analyse it.
There is an issue with your setup which is constantly prompting for updates more frequent than 7 days.

**Comment by MikeWilliams-UK** [comment] 2019-10-14 13:33
If you look at the Edu Geek forum at http://www.edugeek.net/forums/links/191722-your-chemists-chem4word.html you will see that we already have users deploying Chem4Word via SCCM, therefore your issue of permanent update nagging is most likely caused by a clash between Chem4Word and your deployment scenario.

Chem4Word requires read/write access to certain folders and registry locations in order to perform normally.

**Comment by MikeWilliams-UK** [comment] 2019-10-14 14:08
> There is also the added problem of being unable to install the new versions since our users are blocked by Group Policies. Even if the user chooses the "Update Now" option he would still be unable to update the application. So again, in this scenario, the auto update option should have the option of being disabled since the pop-up will appear without any functionality (because of the Group Policies on our part). We understand that your team is small and we can wait for a new version that adds this option in the future.

You have contadicted what you said earlier.  You said that once the user had updated they were in a loop because SCCM downgraded them to the previous version, but you have just said that they can't update!

**Comment by MikeWilliams-UK** [comment] 2019-10-14 15:22
We would very much like to work with you on solving the issue,
However we can't do this blind.

Once you provide us with the logs we will be able to look into this.

**Comment by MikeWilliams-UK** [comment] 2020-01-09 14:57
Closing this issue as user has not provided us with the logs.

**Closed by MikeWilliams-UK** 2020-01-09 14:57 UTC
Labels: Bug, Help Wanted, Unable to Reproduce
